name: ecommerce_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  convex_bottom_bar: ^3.2.0
  flutter:
    sdk: flutter
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Bold.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-Regular.ttf
