// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT70LxogcGVtQm5byRO7SWXSygaRRixLU',
    appId: '1:17829340876:web:816e94097d11676ef88469',
    messagingSenderId: '17829340876',
    projectId: 'ecommerce-shoppers',
    authDomain: 'ecommerce-shoppers.firebaseapp.com',
    storageBucket: 'ecommerce-shoppers.appspot.com',
    measurementId: 'G-P94EWBZCHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3s1rve2X9LHR539L5ZSv_I8zTb9Dercg',
    appId: '1:17829340876:android:1a24cf70920b3d2cf88469',
    messagingSenderId: '17829340876',
    projectId: 'ecommerce-shoppers',
    storageBucket: 'ecommerce-shoppers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSud_CSlA5DirhAMPOLpNg5GysW51uyTo',
    appId: '1:17829340876:ios:24d89c156796cd65f88469',
    messagingSenderId: '17829340876',
    projectId: 'ecommerce-shoppers',
    storageBucket: 'ecommerce-shoppers.appspot.com',
    iosBundleId: 'com.example.ecommerceUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSud_CSlA5DirhAMPOLpNg5GysW51uyTo',
    appId: '1:17829340876:ios:48b5dfcbbbb50530f88469',
    messagingSenderId: '17829340876',
    projectId: 'ecommerce-shoppers',
    storageBucket: 'ecommerce-shoppers.appspot.com',
    iosBundleId: 'com.example.ecommerceUi.RunnerTests',
  );
}
